/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ACPPermissionDialog: typeof import('./src/components/chat/ACPPermissionDialog.vue')['default']
    AppearanceSection: typeof import('./src/components/properties/AppearanceSection.vue')['default']
    AppMenu: typeof import('./src/components/AppMenu.vue')['default']
    AppSelect: typeof import('./src/components/AppSelect.vue')['default']
    AppToast: typeof import('./src/components/AppToast.vue')['default']
    CanvasContextMenu: typeof import('./src/components/CanvasContextMenu.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/chat/ChatMessage.vue')['default']
    ChatPanel: typeof import('./src/components/ChatPanel.vue')['default']
    CodePanel: typeof import('./src/components/CodePanel.vue')['default']
    CollabPanel: typeof import('./src/components/CollabPanel.vue')['default']
    ColorInput: typeof import('./src/components/ColorInput.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker.vue')['default']
    DesignPanel: typeof import('./src/components/DesignPanel.vue')['default']
    EditorCanvas: typeof import('./src/components/EditorCanvas.vue')['default']
    EffectsSection: typeof import('./src/components/properties/EffectsSection.vue')['default']
    ExportSection: typeof import('./src/components/properties/ExportSection.vue')['default']
    FillPicker: typeof import('./src/components/FillPicker.vue')['default']
    FillSection: typeof import('./src/components/properties/FillSection.vue')['default']
    FontPicker: typeof import('./src/components/FontPicker.vue')['default']
    HsvColorArea: typeof import('./src/components/HsvColorArea.vue')['default']
    IconLucideCheck: typeof import('~icons/lucide/check')['default']
    IconLucideChevronRight: typeof import('~icons/lucide/chevron-right')['default']
    IconLucideCopy: typeof import('~icons/lucide/copy')['default']
    IconLucideEyeOff: typeof import('~icons/lucide/eye-off')['default']
    IconLucideFile: typeof import('~icons/lucide/file')['default']
    IconLucidePencilRuler: typeof import('~icons/lucide/pencil-ruler')['default']
    IconLucidePlus: typeof import('~icons/lucide/plus')['default']
    IconLucideSidebar: typeof import('~icons/lucide/sidebar')['default']
    IconLucideTriangleAlert: typeof import('~icons/lucide/triangle-alert')['default']
    IconLucideX: typeof import('~icons/lucide/x')['default']
    LayersPanel: typeof import('./src/components/LayersPanel.vue')['default']
    LayerTree: typeof import('./src/components/LayerTree.vue')['default']
    LayoutSection: typeof import('./src/components/properties/LayoutSection.vue')['default']
    MobileDrawer: typeof import('./src/components/MobileDrawer.vue')['default']
    MobileHud: typeof import('./src/components/MobileHud.vue')['default']
    NodeContextMenuContent: typeof import('./src/components/NodeContextMenuContent.vue')['default']
    PageSection: typeof import('./src/components/properties/PageSection.vue')['default']
    PagesPanel: typeof import('./src/components/PagesPanel.vue')['default']
    PolarisSidebar: typeof import('./src/components/PolarisSidebar.vue')['default']
    PositionSection: typeof import('./src/components/properties/PositionSection.vue')['default']
    PropertiesPanel: typeof import('./src/components/PropertiesPanel.vue')['default']
    ProviderSelect: typeof import('./src/components/chat/ProviderSelect.vue')['default']
    ProviderSettings: typeof import('./src/components/chat/ProviderSettings.vue')['default']
    ProviderSetup: typeof import('./src/components/chat/ProviderSetup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SafariBanner: typeof import('./src/components/SafariBanner.vue')['default']
    ScrubInput: typeof import('./src/components/ScrubInput.vue')['default']
    StrokeSection: typeof import('./src/components/properties/StrokeSection.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    TypographySection: typeof import('./src/components/properties/TypographySection.vue')['default']
    VariablesDialog: typeof import('./src/components/VariablesDialog.vue')['default']
    VariablesSection: typeof import('./src/components/properties/VariablesSection.vue')['default']
  }
}
